version: 2
jobs:
  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter -v build apk
workflows:
  version: 2
  build_and_test:
    jobs:
    - test
    - build
