version: 2.1

exectors:
  flutter-exec:
    docker:
    - image: cirrusci/flutter

jobs:
  check_dependencies:
    executor: flutter-exec
    steps:
      - checkout
      - run: flutter doctor
  test:
    executor: flutter-exec
    steps:
    - checkout
    - run: flutter test
  style:
    executor: flutter-exec
    steps:
    - checkout
    - run: flutter analyze
  deploy-android:
    executor: flutter-exec
    steps:
      - checkout
      - run: flutter -v build apk
      - store_artifacts:
          path: build/app/outputs/apk/debug/app-debug.apk
workflows:
  version: 2
  full:
    jobs:
    - check_dependencies
    - test
      requires:
        - check_dependencies
    - style
      requires:
        - check_dependencies
    - deploy
      requires:
        - test
        - style
